# Generated by Django 4.2.16 on 2024-09-06 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, choices=[('GPT-3(Legacy)', 'GPT-3(Legacy)'), ('GPT-4', 'GPT-4'), ('GPT-4 Turbo', 'GPT-4 Turbo'), ('GPT-4o', 'GPT-4o'), ('GPT-4o-mini', 'GPT-4o-mini')], max_length=255, null=True)),
                ('role', models.CharField(blank=True, choices=[('Business Analyst', 'Business Analyst'), ('Customer Service Representative', 'Customer Service Representative'), ('Fitness Instructor', 'Fitness Instructor'), ('Educational Tutor', 'Educational Tutor'), ('Entertainment Host', 'Entertainment Host'), ('Healthcare Assistant', 'Healthcare Assistant'), ('Technical Helpdesk', 'Technical Helpdesk'), ('Artistic Consultant', 'Artistic Consultant')], max_length=255, null=True)),
                ('personality', models.CharField(blank=True, choices=[('Professional & Efficient', 'Professional & Efficient'), ('Friendly & Responsive', 'Friendly & Responsive'), ('Analytical & Trustworthy', 'Analytical & Trustworthy'), ('Motivational & Energetic', 'Motivational & Energetic'), ('Witty & Sarcastic', 'Witty & Sarcastic'), ('Compassionate & Knowledgeable', 'Compassionate & Knowledgeable'), ('Technical & Patient', 'Technical & Patient'), ('Innovative & Creative', 'Innovative & Creative')], max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bot_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
